# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
    paths: [apis/userprofile/**,.github/workflows/prod-build-node.yml]
  pull_request:
    branches: [ master ]
    paths: [apis/userprofile/**,.github/workflows/prod-build-node.yml]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --prefix apis/userprofile
    - run: npm run build --prefix apis/userprofile --if-present
    - run: npm test --prefix apis/userprofile
    - name: Create issue on build failure
      if: ${{ failure() }}
      uses: JasonEtco/create-an-issue@v2.4.0
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
